### ISSUE TITLE
Latest Update made the Card go blank and causes the Overview page to go Blank too

### ISSUE THREAD

**Issue by LokeYourC3PH** [dnguyen800/air-visual-card#67]
What the title says. After updating to the latest version about 9-10 hours ago, the card is now completely blank, and the Dashboard/Overview panel where it is located also does not show up until I do a CTRL+F5 to force reload it. Then I can see everything, and the card itself is basically a 1px empty line, and I had to configure the Dashboard/Overview to remove it for everything to work normally again.

**Comment by LokeYourC3PH** [comment]
Note: Adding it back manually after removing it makes the Dashboard go completely blank and you need to remove it via the "Raw Configuration Editor". This is pretty bad.

**Comment by Chreece** [comment]
Which integration are you using?

**Comment by LokeYourC3PH** [comment]
> Which integration are you using?

Didn't get it at first, my bad.

HACS, I use the HACS version.

**Comment by ytilis** [comment]
Chiming in that I'm seeing the same thing. I use Home Assistant Sections and the entire section containing the card becomes blank. The rest of my dashboard was unaffected, just the section containing the card. Editing the Section in YAML mode to remove the card fixed the Section, though as with the original issue reporter, trying to re-add the card only causes it to fail to render again.

I'm seeing the following console error in the frontend when the card is on the page:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')
    at set hass (air-visual-card.js?hacstag=157674859204:396:68)
    at i.value (hui-card.ts:126:21)
    at i.value (hui-card.ts:42:10)
    at i.value (hui-section.ts:70:13)
    at hui-section.ts:277:12
    at Array.map (<anonymous>)
    at i.value (hui-section.ts:276:32)
    at i.value (hui-section.ts:198:10)
    at i.value (hui-section.ts:98:12)
    at i.performUpdate (reactive-element.ts:1327:14)
```
The problem on this line:
https://github.com/dnguyen800/air-visual-card/blob/202fba6b2805a4db3959ee2e6f1018d24e23fade/dist/air-visual-card.js#L396

You're checking to make sure that `weatherEntity` is defined, there's no check to make sure that `hass.states[weatherEntity]` exists. This is happening because you're using `weather.home` as the default weather value on this line:
https://github.com/dnguyen800/air-visual-card/blob/202fba6b2805a4db3959ee2e6f1018d24e23fade/dist/air-visual-card.js#L41

My weather entity has a different id. So the if statement sees the default value of `weather.home` you've provided in the config, but if the end-user has a different weather entity name, this will fail because there is no state for this non-existant entity.

The bet solution, honestly, is probably not to set a default weather entity value and allow the user to select one when they set the card. But since many users probably already have this non-existent entity in their configs due to this default, you'll need to confirm that the entity exists, unless there's a way to do a config migration to remove weather.home if it doesn't exist. IDK how much power HACS gives you to modify existing configs.

**Comment by Chreece** [comment]
Yes you are right, the weather entity check should return '' if no none is given. 
I will try to make a PR in the afternoon to fix that problem. Sorry for that 😔

**Comment by Chreece** [comment]
Could you please test the card from my repo:
https://github.com/Chreece/air-visual-card 
Please clean browser cache afterwards (shift+f5)

**Comment by LokeYourC3PH** [comment]
I mean in my case, my Weather Integration is PirateWeather, which is quite different from (and better in every way) the default weather integration, which if this card requires the default weather integration to be present all of a sudden, would make sense for why it fails.

**Comment by Chreece** [comment]
@LokeYourC3PH still after the changes on my repo you have the same error?

**Comment by LokeYourC3PH** [comment]
> @LokeYourC3PH still after the changes on my repo you have the same error?

I only use HACS and never manually install plugins, so I cannot test your repo. Gotta wait for ytilis to confirm.

**Comment by Chreece** [comment]
HACS is using repos though. 
But I understand, you can wait for others to test...

**Comment by LokeYourC3PH** [comment]
> HACS is using repos though. But I understand, you can wait for others to test...

You're right, I could try to manually add your Repo and see if it works, no promises though 👍

**Comment by Chreece** [comment]
It's not an integration but front-end, I don't know how it's in English

**Comment by LokeYourC3PH** [comment]
> It's not an integration but front-end, I don't know how it's in English

I see, there's the following options:
![image](https://github.com/user-attachments/assets/6c58732d-7e87-4ed9-b992-c91db23683f2)

According to what you say, I would assume Dashboard, so I will try that.

**Comment by Chreece** [comment]
Exactly, dashboard

**Comment by LokeYourC3PH** [comment]
> Exactly, dashboard

![image](https://github.com/user-attachments/assets/d1a65686-42da-4681-b15a-6d22527be187)

Yup, your commit fixed it.

**Comment by Chreece** [comment]
Are you using the WAQI integration? You should also have the text (Excellent|Good etc) above the PM2.5

**Comment by LokeYourC3PH** [comment]
> Are you using the WAQI integration? You should also have the text (Excellent|Good etc) above the PM2.5

I'm using the [AirVisual Cloud Integration](https://www.home-assistant.io/integrations/airvisual)

**Comment by Chreece** [comment]
I'm happy that AirVisual and the PirateWeather works better for you. My concern is that you don't get the text above the pm2.5 because you should have...
I'll have to look on that... Can you give me the attributes from the sensor you are using for AQI?

**Comment by LokeYourC3PH** [comment]
> I'm happy that AirVisual and the PirateWeather works better for you. My concern is that you don't get the text above the pm2.5 because you should have... I'll have to look on that... Can you give me the attributes from the sensor you are using for AQI?

Here you go:

![image](https://github.com/user-attachments/assets/faa278e6-5f23-4fca-b4b1-a6cefd03374e)

**Comment by ntlgr** [comment]
Having the same problem.

**Comment by LokeYourC3PH** [comment]
> > Having the same problem.
> 
> please read the conversation above
> 
> @LokeYourC3PH can you update your card from my repo?

Done, testing now.

**Comment by LokeYourC3PH** [comment]
> > Having the same problem.
> 
> please read the conversation above
> 
> @LokeYourC3PH can you update your card from my repo?

@Chreece This is the outcome of that update:
![image](https://github.com/user-attachments/assets/b4dbdda5-6695-460f-9ddd-7265518f1626)

**Comment by Chreece** [comment]
please make sure that AirVisual integration has values on it's entities

**Comment by LokeYourC3PH** [comment]
> please make sure that AirVisual integration has values on it's entities
> 
> Edit: Fixed... Please update now

Yep, works ^^

![image](https://github.com/user-attachments/assets/6f0662e2-472e-4d98-8d31-1d1ac1be4eca)

**Comment by LokeYourC3PH** [comment]
> please make sure that AirVisual integration has values on it's entities
> 
> Edit: Fixed... Please update now

Will the fixes be added to this original repo, or should I keep using your repo for the time being?

**Comment by Chreece** [comment]
> Will the fixes be added to this original repo, or should I keep using your repo for the time being?
That's up to @dnguyen800, the [PR](https://github.com/dnguyen800/air-visual-card/pull/68) is waiting to be merged
